version: "2"
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: ganex/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data/conf:/etc/openvpn

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9001
